[package]
name = "gpu_fan_ctrl"
version = "0.1.0"
edition = "2021"

[dependencies]
nvml-wrapper = "0.10"
clap = { version = "4", features = ["derive"] }
log = "0.4"
env_logger = "0.10"
chrono = "0.4"
ctrlc = "3.4"
nvml = "0.0.2"
